langauge: ruby

dist: trusty
sudo: false

cache:
  yarn: true
  bundler: true

before_script:
  - cp config/travis.database.yml config/database.yml
  - nvm install 6
  - ./bin/setup

branches:
  only:
    - master
